return {
	debug        = require "std51.debug.debug",
	getfenv      = require "std51.debug.getfenv",
	gethook      = require "std51.debug.gethook",
	getinfo      = require "std51.debug.getinfo",
	getlocal     = require "std51.debug.getlocal",
	getmetatable = require "std51.debug.getmetatable",
	getregistry  = require "std51.debug.getregistry",
	getupvalue   = require "std51.debug.getupvalue",
	setfenv      = require "std51.debug.setfenv",
	sethook      = require "std51.debug.sethook",
	setlocal     = require "std51.debug.setlocal",
	setmetatable = require "std51.debug.setmetatable",
	setupvalue   = require "std51.debug.setupvalue",
	traceback    = require "std51.debug.traceback",
};
