return {
	assert         = require "std51.base.assert",
	collectgarbage = require "std51.base.collectgarbage",
	dofile         = require "std51.base.dofile",
	error          = require "std51.base.error",
	getfenv        = require "std51.base.getfenv",
	getmetatable   = require "std51.base.getmetatable",
	ipairs         = require "std51.base.ipairs",
	load           = require "std51.base.load",
	loadfile       = require "std51.base.loadfile",
	loadstring     = require "std51.base.loadstring",
	module         = require "std51.base.module",
	newproxy       = require "std51.base.newproxy",
	next           = require "std51.base.next",
	pairs          = require "std51.base.pairs",
	pcall          = require "std51.base.pcall",
	print          = require "std51.base.print",
	rawequal       = require "std51.base.rawequal",
	rawget         = require "std51.base.rawget",
	rawset         = require "std51.base.rawset",
	require        = require "std51.base.require",
	select         = require "std51.base.select",
	setfenv        = require "std51.base.setfenv",
	setmetatable   = require "std51.base.setmetatable",
	tonumber       = require "std51.base.tonumber",
	tostring       = require "std51.base.tostring",
	type           = require "std51.base.type",
	unpack         = require "std51.base.unpack",
	xpcall         = require "std51.base.xpcall",

	-- Deprecated in Lua 5.1
	gcinfo         = require "std51.base.gcinfo",
};
