return {
	abs        = require "std51.math.abs",
	acos       = require "std51.math.acos",
	asin       = require "std51.math.asin",
	atan       = require "std51.math.atan",
	atan2      = require "std51.math.atan2",
	ceil       = require "std51.math.ceil",
	cos        = require "std51.math.cos",
	cosh       = require "std51.math.cosh",
	deg        = require "std51.math.deg",
	exp        = require "std51.math.exp",
	floor      = require "std51.math.floor",
	fmod       = require "std51.math.fmod",
	frexp      = require "std51.math.frexp",
	huge       = require "std51.math.huge",
	ldexp      = require "std51.math.ldexp",
	log        = require "std51.math.log",
	log10      = require "std51.math.log10",
	max        = require "std51.math.max",
	min        = require "std51.math.min",
	modf       = require "std51.math.modf",
	pi         = require "std51.math.pi",
	pow        = require "std51.math.pow",
	rad        = require "std51.math.rad",
	random     = require "std51.math.random",
	randomseed = require "std51.math.randomseed",
	sin        = require "std51.math.sin",
	sinh       = require "std51.math.sinh",
	sqrt       = require "std51.math.sqrt",
	tan        = require "std51.math.tan",
	tanh       = require "std51.math.tanh",

	-- Renamed in Lua 5.1
	mod        = require "std51.math.mod",
};
